Repository NextGenDevOrg/02-CSS-Learning, pull requests merged in 2021-12, with the labels that each got.

#36 Created a Product card UI Design
  tasks-by-users/AbbasShaikh0304/10-Product Card UI Design/Shoe.png
  tasks-by-users/AbbasShaikh0304/10-Product Card UI Design/index.html
  tasks-by-users/AbbasShaikh0304/10-Product Card UI Design/style.css
Labels: documentation

#39 added html and css
  tasks-by-users/nehalskdev/01-ecommerce-website/index.html
  tasks-by-users/nehalskdev/01-ecommerce-website/style.css
Labels: documentation, enhancement, good first issue

#19 02 css ecommerce product details
  tasks-by-users/mmusk/02-second-task-css/index.html
  tasks-by-users/mmusk/02-second-task-css/product details.html
  tasks-by-users/mmusk/02-second-task-css/products.html
  tasks-by-users/mmusk/02-second-task-css/style.css
Labels: enhancement

#10 custom-select-box
  tasks-by-users/muzeeb100/Custom Select Box css/index.html
  tasks-by-users/muzeeb100/Custom Select Box css/style.css
Labels: enhancement

#6 rectangle in the circle
  tasks-by-users/muzeeb100/rectangle in the circle/index.html
  tasks-by-users/muzeeb100/rectangle in the circle/style.css
Labels: enhancement
